services:
  - type: web
    name: gather-notify-bot
    runtime: node
    buildCommand: npm install
    startCommand: node bot.js
    envVars:
      - key: GATHER_API_KEY
        value: 5y3xKlHUiEBYeTMq
      - key: GATHER_SPACE_ID
        value: 4601933d-6215-4853-9f04-aa1d7d5fba92
      - key: NODE_ENV
        value: production
    plan: free
